server:
  port: 8080

spring:
  data-source:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000
  mail:
    host: smtp.gmail.com
    port: 587
    username: mittul.store.liquor@gmail.com
    password: lyadufzwgkgnfbum
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  account_sid: ACbc1a35dc5c725cc49b2d0e8b00271522
  auth_token: eedd470c5885da7be963252d22eaed75
  trial_number: +14256007803